version: '3.9'

services:
  guacd:
    image: guacamole/guacd:latest
    container_name: guacamole-guacd
    restart: unless-stopped
    volumes:
      - ./guacamole/record:/record
      - ./guacamole/drive:/drive
    ports:
      - "4822:4822"

  guacamole:
    image: guacamole/guacamole:latest
    container_name: guacamole-web
    restart: unless-stopped
    depends_on:
      - guacd
      - postgres
    environment:
      - GUACD_HOSTNAME=guacd
      - GUACD_PORT=4822
      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_DATABASE=guacamole_db
      - POSTGRES_USER=guacamole_user
      - POSTGRES_PASSWORD=guacamole_password
    ports:
      - "8080:8080"
    volumes:
      - ./guacamole/extensions:/extensions
      - ./guacamole/guac-home:/guac-home

  postgres:
    image: postgres:15
    container_name: guacamole-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=guacamole_db
      - POSTGRES_USER=guacamole_user
      - POSTGRES_PASSWORD=guacamole_password
      - PGDATA=/var/lib/postgresql/data/guacamole
    volumes:
      - ./guacamole/db:/var/lib/postgresql/data
      - ./guacamole/init:/docker-entrypoint-initdb.d
