version: "3.9"

services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    network_mode: host
    privileged: true
    ports:
      - "8123:8123"   # Webové rozhraní Home Assistantu
    environment:
      - TZ=Europe/Prague
    volumes:
      - ./config:/config
