# online knihovna

version: "3.9"

services:
  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - TZ=Europe/Prague     # nastav si správnou časovou zónu
    volumes:
      - /path/to/your/books:/manga              # sem dej složku s PDF/e-knihami
      - /path/to/your/kavita/config:/kavita/config  # složka pro konfiguraci a databázi
