services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        limits:
          memory: 16G

  openwebui:
      image: ghcr.io/open-webui/open-webui
      ports:
        - "3000:8080"
      environment:
        - OLLAMA_BASE_URL=http://ollama:11434
      depends_on:
        - ollama

volumes:
  ollama:

# jak spustit model:
# docker exec -it ollama ollama pull llama3.1:8b
# docker exec -it ollama ollama run llama3.1:8b
