version: "3.9"

services:
  mariadb:
    image: mariadb:11.4
    container_name: moodle-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: superrootpass
      MARIADB_DATABASE: moodle
      MARIADB_USER: moodle
      MARIADB_PASSWORD: moodlepass
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - moodle-net

  moodle:
    image: moodlehq/moodle-php-apache:8.2
    container_name: moodle
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - "8080:80"
    volumes:
      - ./moodle-code:/var/www/html      # připojíme kód Moodle
      - moodle_data:/var/www/moodledata
    networks:
      - moodle-net
      - proxy   # tvoje existující síť

volumes:
  mariadb_data:
  moodle_data:

networks:
  moodle-net:
    driver: bridge
  proxy:
    external: true
