# stremování filmů, seriálů a hudby

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: 1000:1000
    ports:
      - "8096:8096"
    volumes:
      - /data/jellyfin/config:/config
      - /data/jellyfin/cache:/cache
      - /data/media/movies:/media/movies
      - /data/media/series:/media/series
      - /data/media/music:/media/music
    restart: unless-stopped
