FROM jupyterhub/jupyterhub:4.0

USER root

RUN apt-get update && apt-get install -y git

COPY requirements.txt /tmp/requirements.txt

RUN pip install --no-cache-dir -r /tmp/requirements.txt

USER jovyan
