FROM jupyter/minimal-notebook:python-3.11

USER root

RUN apt-get update && apt-get install -y \
    git \
    && rm -rf /var/lib/apt/lists/*

USER jovyan

RUN pip install \
    ipywidgets \
    rise \
    jupyterlab-git \
    nbgrader \
    black \
    flake8 \
    jupyterlab-code-formatter

# aktivace widgetů
RUN jupyter nbextension enable --py widgetsnbextension

# formatter integrace
RUN jupyter server extension enable --py jupyterlab_code_formatter

# black formatter
RUN pip install black
