version: "3"

services:
  jupyterhub:
    build: .
    container_name: jupyterhub
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./jupyterhub:/srv/jupyterhub
      - /var/run/docker.sock:/var/run/docker.sock
      - jupyterhub-data:/data
    environment:
      DOCKER_JUPYTER_IMAGE: course-notebook
      DOCKER_NETWORK_NAME: jupyterhub-network
    networks:
      - jupyterhub-network

volumes:
  jupyterhub-data:

networks:
  jupyterhub-network:
